[package]
name = "virtio"
version = "0.1.0"
authors = ["Conrad Grobler <grobler@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = { version = "*", default-features = false }
bitflags = "*"
num_enum = { version = "*", default-features = false }
rust-hypervisor-firmware-subset = { path = "../../third_party/rust-hypervisor-firmware-subset" }
