[package]
name = "fuzzable"
version = "0.1.0"
authors = ["Razieh Behjati <razieh@google.com>"]
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
oak_functions = { path = "../../../sdk/oak_functions" }
prost = "*"

[dev-dependencies]
log = "*"
maplit = "*"
oak_functions_abi = { path = "../../../abi" }
oak_functions_loader = { path = "../../../loader" }
oak_functions_lookup = { path = "../../../lookup" }
oak_functions_metrics = { path = "../../../experimental/metrics" }
oak_functions_workload_logging = { path = "../../../workload_logging" }
rand = "0.8.4"
test_utils = { path = "../../../sdk/test_utils" }
tokio = { version = "*", features = ["macros"] }

[build-dependencies]
prost-build = "*"
