[package]
name = "oak_runtime"
version = "0.1.0"
authors = [
  "David Drysdale <drysdale@google.com>",
  "Ben Blaxill<benblaxill@google.com>"
]
edition = "2018"
license = "Apache-2.0"

[features]
test_build = []
default = []

[dependencies]
# Note that if new dependencies are added here:
#  - they need to be synced to //cargo/Cargo.toml
#  - `cd cargo && cargo raze` needs re-running, and the results checked in
byteorder = { version = "*", default-features = false }
http = "*"
hyper = "*"
itertools = "*"
lazy_static = "*"
log = { version = "*" }
oak_abi = "=0.1.0"
prost = "*"
prost-types = "*"
rand = "*"
tokio = { version = "*", features = ["rt-core", "macros"] }
wasmi = { version = "*", default-features = false, features = ["core"] }
prometheus = { version = "0.8", features = [
  "nightly"
], default-features = false }
futures = "*"

[dev-dependencies]
maplit = "*"
wat = "*"
simple_logger = "*"

[build-dependencies]
oak_utils = "*"
prost-build = "*"
