[package]
name = "oak_runtime"
version = "0.1.0"
authors = [
  "David Drysdale <drysdale@google.com>",
  "Ben Blaxill<benblaxill@google.com>"
]
edition = "2018"
license = "Apache-2.0"

[features]
std = ["no-std-compat/std"]
default = ["std"]

[dependencies]
byteorder = { version = "*", default-features = false }
itertools = "*"
log = { version = "*" }
oak_abi = "=0.1.0"
prost = "*"
rand = { version = "*", default-features = false, features = ["alloc"] }
wasmi = { version = "*", default-features = false, features = ["core"] }
no-std-compat = { version = "0.2.0", features = ["alloc", "compat_hash"] }

[dev-dependencies]
maplit = "*"

[build-dependencies]
oak_utils = "*"
prost-build = "*"
