[package]
name = "hello_world"
version = "0.1.0"
authors = ["Tiziano Santoro <tzn@google.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "*"
oak = "=0.1.0"
oak_derive = "=0.1.0"
oak_log = "=0.1.0"
protobuf = "*"
translator_common = "=0.1.0"

[dev-dependencies]
assert_matches = "*"
oak_abi = "=0.1.0"
oak_runtime = "=0.1.0"
oak_tests = "=0.1.0"
serial_test = "*"
serial_test_derive = "*"
simple_logger = "*"

[build-dependencies]
oak_utils = "*"
protoc-rust-grpc = { path = "../../../../third_party/grpc-rust/protoc-rust-grpc" }
