[package]
name = "oak_containers_orchestrator"
version = "0.1.0"
authors = ["Juliette Pretot <julsh@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
clap = { version = "*", features = ["derive"] }
oak_containers_orchestrator_client = { workspace = true }
tokio = { version = "*", features = ["rt-multi-thread", "macros", "sync", "fs", "process"] }
log = "*"
syslog = "*"
tar = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
