[package]
name = "oak_containers_orchestrator"
version = "0.1.0"
authors = ["Juliette Pretot <julsh@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
clap = { version = "*", features = ["derive"] }
futures = "*"
log = "*"
oak_containers_orchestrator_client = { workspace = true }
oak_crypto = { workspace = true }
oak_remote_attestation = { workspace = true }
prost = "*"
prost-types = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
syslog = "*"
tar = "*"
tokio = { version = "*", features = [
  "rt-multi-thread",
  "macros",
  "sync",
  "fs",
  "process",
  "net",
] }
tokio-stream = { version = "*", features = ["net"] }
tonic = { workspace = true }

[build-dependencies]
oak_grpc_utils = { workspace = true }
