[package]
name = "oak_kernel_measurement"
version = "0.1.0"
authors = ["Conrad Grobler <grobler@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
clap = { version = "*", features = ["derive"] }
env_logger = "*"
hex = "*"
log = "*"
sha2 = "*"
static_assertions = "*"
strum = { version = "*", default-features = false, features = ["derive"] }
zerocopy = "*"
