[package]
name = "split_grpc_client"
version = "0.1.0"
authors = ["Conrad Grobler <grobler@google.com>"]
edition = "2018"

[dependencies]
env_logger = "*"
log = "*"
prost = "*"
tokio = { version = "*", features = ["fs", "macros"] }
tonic = { version = "*", features = ["tls"] }

[build-dependencies]
tonic-build = "*"
