[package]
name = "uefi-proto"
version = "0.1.0"
authors = ["Andri Saar <andrisaar@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
prost = "*"
tonic = "*"

[build-dependencies]
tonic-build = "*"
