name = "abitest"

[application]
variant = "rust"
manifest = "examples/abitest/config/config.toml"
out = "examples/abitest/bin/config.bin"

[modules]
module_0 = { Cargo = { cargo_manifest = "examples/abitest/module_0/rust/Cargo.toml" } }
module_1 = { Cargo = { cargo_manifest = "examples/abitest/module_1/rust/Cargo.toml" } }

[clients]
cpp = { Bazel = { bazel_target = "//examples/abitest/client:client" }, additional_args = [
  "--test_exclude=Storage",
  "--cert_chain=../../../../../../../../examples/certs/local/local.pem",
  "--private_key=../../../../../../../../examples/certs/local/local.key",
] }
