[workspace]

[package]
name = "oak_io"
version = "0.1.0"
authors = ["Conrad Grobler <grobler@google.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
oak_abi = { path = "../oak_abi" }

[patch.crates-io]
prost = { path = "../third_party/prost" }
prost-build = { path = "../third_party/prost/prost-build" }
prost-derive = { path = "../third_party/prost/prost-derive" }
prost-types = { path = "../third_party/prost/prost-types" }
