[package]
name = "oak_remote_attestation"
version = "0.1.0"
authors = ["Ivan Petrov <ivanpetrov@google.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
default = ["ring-crypto"]
std = ["anyhow/std"]
ring-crypto = ["ring"]
rust-crypto = ["aes-gcm", "hkdf", "p256", "sha2", "signature", "x25519-dalek"]

[dependencies]
aes-gcm = { version = "*", optional = true }
anyhow = { version = "*", default-features = false }
bytes = { version = "*", default-features = false }
hkdf = { version = "*", optional = true }
p256 = { version = "*", default-features = false, optional = true, features = [
  "ecdsa"
] }
ring = { path = "../../third_party/ring", default-features = false, optional = true }
sha2 = { version = "*", optional = true, default-features = false }
signature = { version = "*", optional = true, default-features = false }
x25519-dalek = { path = "../../third_party/x25519-dalek", optional = true, default-features = false, features = [
  "u64_backend"
] }

[dev-dependencies]
assert_matches = "*"
quickcheck = "*"
quickcheck_macros = "*"

# TODO(#2879): figure out why `cargo-udeps` thinks these (used) dependencies are unused
[package.metadata.cargo-udeps.ignore]
normal = ["aes-gcm", "hkdf", "p256", "sha2", "signature", "x25519-dalek"]
