[package]
name = "oak_tests"
version = "0.1.0"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
lazy_static = "1.4"
log = { version = "^0.4.0", features = ["std"] }
oak_derive = { path = "../oak_derive"}
oak = { path = "../oak"}
protobuf = "*"
rand = { version = "0.7", features = ["std"] }
simple_logger = "1"

[build-dependencies]
protoc-rust = "*"
