[package]
name = "oak_baremetal_app_qemu"
version = "0.1.0"
authors = ["Andri Saar <andrisaar@google.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
default = ["pvh", "virtio_console_channel"]
pvh = ["rust-hypervisor-firmware-boot/pvh"]
multiboot = []
serial_channel = ["oak_baremetal_kernel/serial_channel"]
simple_io_channel = ["oak_baremetal_kernel/simple_io_channel"]
virtio_console_channel = ["oak_baremetal_kernel/virtio_console_channel"]

[dependencies]
bitflags = "*"
oak_baremetal_kernel = { path = "../../experimental/oak_baremetal_kernel" }
rust-hypervisor-firmware-boot = { path = "../../third_party/rust-hypervisor-firmware-boot", default-features = false }

[build-dependencies]
bindgen = "*"

[patch.crates-io]
# Ensure no_std compatibility. TODO(#2920): remove once https://github.com/google/flatbuffers/pull/7338 is merged.
flatbuffers = { git = "https://github.com/jul-sh/flatbuffers.git", rev = "a07ddee936737da89aeb5a496f9742a805537188" }
# Ensure no_std compatibility. Dependency of flatbuffers. TODO(#2920): remove once https://github.com/bbqsrc/thiserror-core2/pull/3 is merged.
thiserror_core2 = { git = "https://github.com/jul-sh/thiserror-core2.git", rev = "b99e1a0106623cbbd12cbb5562d01df7a3fdc22e" }

[[bin]]
name = "oak_baremetal_app_qemu"
test = false
bench = false
