[package]
name = "abitest_1_backend"
version = "0.1.0"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
log = "*"
abitest_common = { path = "../../abitest_common" }
oak = "*"
oak_log = "*"
protobuf = "*"
fidl = {path = "../../../../third_party/fidl"}
