[package]
name = "abitest_1_backend"
version = "0.1.0"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
log = "*"
abitest_common = { path = "../../abitest_common" }
oak = { path = "../../../../sdk/rust/oak", features = ["linear-handles"] }
oak_abi = { path = "../../../../oak_abi" }
oak_io = { path = "../../../../oak_io" }
prost = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
