[workspace]
members = [
  "abi",
  "client/rust/Cargo.toml",
  "examples/abitest/backend",
  "examples/abitest/client",
  "examples/abitest/module",
  "examples/benchmark/module",
  "examples/fuzzable/module",
  "examples/key_value_lookup/module",
  "examples/mobilenet/client/rust",
  "examples/mobilenet/module",
  "examples/metrics/client/rust",
  "examples/metrics/module",
  "examples/weather_lookup/module",
  "load_test",
  "loader",
  "loader/fuzz",
  "location_utils",
  "lookup_data_generator",
  "sdk/oak_functions",
  "sdk/oak_functions/tests/module",
  "sdk/test_utils",
]
