# Configuration used for dependency checking with cargo-deny.
#
# For further details on all configuration options see:
# https://embarkstudios.github.io/cargo-deny/checks/cfg.html
targets = [{ triple = "x86_64-unknown-linux-musl" }]

# Deny all advisories unless explicitly ignored.
[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
  # TODO(#2258): Remove once tract-tensorflow is updated
  "RUSTSEC-2021-0065",
  # TODO(#2353): Remove once chrono is updated.
  "RUSTSEC-2020-0159",
  "RUSTSEC-2020-0071",
  # TODO(#2421): Remove when no longer required.
  "RUSTSEC-2021-0127",
]

# Deny multiple versions unless explicitly skipped.
[bans]
multiple-versions = "allow"
wildcards = "allow"

# List of allowed licenses.
# For more detailed information see http://go/thirdpartylicenses.
[licenses]
allow = ["Apache-2.0", "MPL-2.0", "MIT", "ISC", "OpenSSL", "Zlib"]
copyleft = "deny"

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 3171872035 }]
