[package]
name = "oak_functions_launcher"
version = "0.1.0"
authors = ["Andri Saar <andrisaar@google.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
grpc-web = ["tonic-web"]

[dependencies]
anyhow = "*"
async-trait = "*"
bmrng = "*"
clap = { version = "*", features = ["derive"] }
command-fds = { version = "*", features = ["tokio"] }
futures = "*"
log = "*"
env_logger = "*"
prost = "*"
serde = "*"
tokio = { version = "*", features = [
  "rt-multi-thread",
  "macros",
  "net",
  "process",
  "signal",
  "sync",
] }
tonic = "*"
tonic-web = { version = "*", optional = true }
oak_functions_abi = { path = "../oak_functions_abi" }
oak_remote_attestation_noninteractive = { path = "../oak_remote_attestation_noninteractive" }
micro_rpc = { path = "../micro_rpc" }
oak_channel = { path = "../oak_channel", features = ["client"] }
hashbrown = "*"

[build-dependencies]
micro_rpc_build = { path = "../micro_rpc_build" }

[dev-dependencies]
lazy_static = "*"
