[package]
name = "oak_functions_launcher"
version = "0.1.0"
authors = ["Andri Saar <andrisaar@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
async-trait = "*"
bmrng = "*"
clap = { version = "*", features = ["derive"] }
command-fds = { version = "*", features = ["tokio"] }
futures = "*"
log = "*"
env_logger = "*"
prost = { workspace = true }
serde = "*"
tokio = { version = "*", features = [
  "rt-multi-thread",
  "macros",
  "net",
  "process",
  "signal",
  "sync",
] }
tonic = "*"
tonic-web = { version = "*", optional = true }
oak_functions_abi = { path = "../oak_functions_abi" }
oak_launcher_utils = { path = "../oak_launcher_utils" }
oak_remote_attestation_noninteractive = { path = "../oak_remote_attestation_noninteractive" }
micro_rpc = { workspace = true }
oak_channel = { workspace = true, features = ["client"] }
hashbrown = "*"
ubyte = "*"
async-recursion = "*"

[build-dependencies]
micro_rpc_build = { workspace = true }

[dev-dependencies]
lazy_static = "*"
oak_functions_client = { workspace = true }
oak_functions_test_utils = { workspace = true }
rand = "*"
xtask = { workspace = true }
