[package]
name = "oak_functions_client"
version = "0.1.0"
authors = ["Tiziano Santoro <tzn@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
async-stream = "*"
base64 = "*"
clap = { version = "*", features = ["derive"] }
ecdsa = { version = "*", features = ["verify", "pkcs8", "pem"] }
env_logger = "*"
grpc_attestation = { path = "../../../grpc_attestation/" }
hex = "*"
http = "*"
log = "*"
oak_functions_abi = { path = "../../abi" }
oak_remote_attestation = { path = "../../../remote_attestation/rust/" }
oak_remote_attestation_sessions_client = { path = "../../../remote_attestation_sessions_client/" }
oak_remote_attestation_amd = { path = "../../../oak_remote_attestation_amd/" }
p256 = { version = "*", features = ["ecdsa-core", "ecdsa", "pem"] }
prost = "*"
regex = "*"
serde = "*"
serde_jcs = "*"
serde_json = "*"
sha2 = { version = "*", default-features = false }
signature = "*"
tokio = { version = "*", features = [
  "fs",
  "macros",
  "sync",
  "rt-multi-thread"
] }
tonic = { version = "*", features = ["tls", "tls-roots"] }
async-trait = "*"

[build-dependencies]
oak_utils = { path = "../../../oak_utils" }
