[package]
name = "oak_functions_client"
version = "0.1.0"
authors = ["Tiziano Santoro <tzn@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
async-stream = "*"
env_logger = "*"
grpc_attestation = { path = "../../../grpc_attestation/" }
http = "*"
log = "*"
oak_functions_abi = { path = "../../abi" }
oak_remote_attestation = { path = "../../../remote_attestation/rust/" }
prost = "*"
regex = "*"
structopt = "*"
tokio = { version = "*", features = [
  "fs",
  "macros",
  "sync",
  "rt-multi-thread"
] }
tonic = { version = "*", features = ["tls", "tls-roots"] }

[dev-dependencies]
serde_json = "*" 
assert_matches = "*"
pem = "*"
oak_sign = { path = "../../../oak_sign" }

[build-dependencies]
oak_utils = { path = "../../../oak_utils" }
