[package]
name = "aggregator"
version = "0.1.0"
authors = ["Ivan Petrov <ivanpetrov@google.com>"]
edition = "2018"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aggregator_common = { path = "../../common" }
itertools = "*"
log = "*"
oak = "=0.1.0"
oak_abi = "=0.1.0"
oak_io = "=0.1.0"
prost = "*"
serde = "*"
toml = "*"

[dev-dependencies]
aggregator_grpc = "=0.1.0"
assert_matches = "*"
env_logger = "*"
log = "*"
maplit = "*"
oak_runtime = "=0.1.0"
oak_tests = "=0.1.0"
tokio = { version = "*", features = ["macros", "rt-threaded", "stream"] }
tonic = { version = "*", features = ["tls"] }

[build-dependencies]
oak_utils = "*"
