[package]
name = "oak_functions_client"
version = "0.1.0"
authors = ["Tiziano Santoro <tzn@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
async-stream = "*"
clap = { version = "*", features = ["derive"] }
env_logger = "*"
http = "*"
log = "*"
micro_rpc = { workspace = true }
oak_attestation_verification = { workspace = true }
oak_client = { workspace = true }
oak_functions_abi = { workspace = true }
prost = { workspace = true }
regex = "*"
tokio = { version = "*", features = [
  "fs",
  "macros",
  "sync",
  "rt-multi-thread"
] }
tonic = { version = "*", features = ["tls", "tls-roots"] }
async-trait = "*"
