name = "trusted_information_retrieval"
backend = { Cargo = { cargo_manifest = "examples/trusted_information_retrieval/backend/Cargo.toml" }, additional_args = [
  "--grpc-tls-private-key=./examples/certs/local/local.key",
  "--grpc-tls-certificate=./examples/certs/local/local.pem",
] }

[application]
variant = "rust"
manifest = "examples/trusted_information_retrieval/config/config.toml"
out = "examples/trusted_information_retrieval/bin/config.bin"

[server]
additional_args = [
  "--config-files=config=examples/trusted_information_retrieval/database.toml",
]

[modules]
module_0 = { Cargo = { cargo_manifest = "examples/trusted_information_retrieval/module_0/rust/Cargo.toml" } }
module_1 = { Cargo = { cargo_manifest = "examples/trusted_information_retrieval/module_1/rust/Cargo.toml" } }

[clients]
cpp = { Bazel = { bazel_target = "//examples/trusted_information_retrieval/client:client" }, additional_args = [
  "--id=1",
] }
