[package]
name = "abitest_0_frontend"
version = "0.1.0"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["oak_runtime/oak-unsafe"]

[dependencies]
abitest_common = { path = "../../abitest_common" }
byteorder = "*"
chrono = "*"
expect = { path = "../../../../third_party/expect" }
hex = "*"
http = "*"
http_server = { path = "../../../http_server/module" }
log = "*"
oak = { version = "=0.1.0", features = ["linear-handles"] }
oak_abi = "=0.1.0"
oak_io = "=0.1.0"
oak_services = "=0.1.0"
prost = "*"
rand_core = "*"
rand = "*"
regex = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tink-proto = "^0.1"

[build-dependencies]
oak_utils = "*"

[dev-dependencies]
anyhow = "*"
abitest_grpc = "=0.1.0"
assert_matches = "*"
env_logger = "*"
log = "*"
maplit = "*"
oak_runtime = "=0.1.0"
oak_tests = "=0.1.0"
tokio = { version = "*", features = ["macros", "rt-threaded", "stream"] }
tonic = { version = "*", features = ["tls"] }
serial_test = "*"
