[package]
name = "oak_containers_syslogd"
version = "0.1.0"
authors = ["Andri Saar <andrisaar@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
bitflags = "*"
clap = { version = "*", features = ["derive"] }
oak_containers_orchestrator_client = { workspace = true }
opentelemetry_api = { version = "*", default-features = false, features = [
  "logs"
] }
opentelemetry_sdk = { version = "*", default-features = false, features = [
  "logs",
  "rt-tokio"
] }
opentelemetry-otlp = { version = "*", default-features = false, features = [
  "logs"
] }
nix = "*"
signal-hook = "*"
signal-hook-tokio = { version = "*", features = ["futures-v0_3"] }
tokio = { version = "*", features = [
  "rt-multi-thread",
  "macros",
  "sync",
  "fs",
  "process",
  "net",
] }
tokio-stream = "*"

[build-dependencies]
oak_grpc_utils = { workspace = true }
