lookup_data_url = "https://storage.googleapis.com/oak_lookup_data/lookup_data_weather"
lookup_data_download_period = "10m"
worker_threads = 4

[metrics]
epsilon = 1.1
batch_size = 20
allowed_labels = ["a"]

[policy]
constant_response_size_bytes = 90
constant_processing_time = "20ms"
