name = "metrics"

[applications]

[applications.rust]
type = "Functions"
wasm_path = "oak_functions/examples/bin/metrics.wasm"
target = { Cargo = { cargo_manifest = "oak_functions/examples/metrics/module/Cargo.toml" } }

[server]
additional_args = [
  "--config-path=./oak_functions/examples/metrics/config.toml"
]

[clients]
rust = { Cargo = { cargo_manifest = "oak_functions/examples/metrics/client/Cargo.toml" }, additional_args = [
  "--uri=http://localhost:8080"
] }
