[package]
name = "lookup_data_generator"
version = "0.1.0"
authors = ["Tiziano Santoro <tzn@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
bytes = "*"
clap = { version = "*", features = ["derive"] }
location_utils = { workspace = true }
multimap = "*"
oak_functions_abi = { workspace = true }
oak_functions_proto = { workspace = true }
prost = { workspace = true }
rand = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
