[package]
name = "lookup_data_generator"
version = "0.1.0"
authors = ["Tiziano Santoro <tzn@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
bytes = "*"
clap = { version = "*", features = ["derive"] }
location_utils = { path = "../location_utils" }
multimap = "*"
oak_functions_abi = { path = "../../oak_functions_abi" }
prost = "*"
rand = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
