name = "translator"

[application]
variant = "rust"
manifest = "examples/translator/config/config.toml"
out = "examples/translator/bin/config.bin"

[modules]
module = { Cargo = { cargo_manifest = "examples/translator/module/rust/Cargo.toml" } }

[clients]
go = { Bazel = { bazel_target = "//examples/translator/client:client" } }
