[package]
name = "oak_baremetal_kernel"
version = "0.1.0"
authors = ["Andri Saar <andrisaar@google.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
default = []
virtio_console_channel = ["virtio"]
vsock_channel = ["virtio"]
serial_channel = []
simple_io_channel = ["oak_baremetal_simple_io"]

[dependencies]
anyhow = { version = "*", default-features = false }
arrayvec = { version = "*", default-features = false }
atomic_refcell = "*"
getrandom = { version = "0.2", features = ["rdrand"] }
lazy_static = { version = "*", features = ["spin_no_std"] }
linked_list_allocator = { version = "*" }
log = "*"
libm = "*"
oak_remote_attestation = { path = "../../remote_attestation/rust", default-features = false, features = [
  "rust-crypto"
] }
oak_remote_attestation_amd = { path = "../../oak_remote_attestation_amd", default-features = false, features = [
  "rust-crypto"
] }
oak_baremetal_communication_channel = { path = "../oak_baremetal_channel" }
oak_baremetal_runtime = { path = "../oak_baremetal_runtime", default-features = false, features = [
  "rust-crypto"
] }
oak_baremetal_simple_io = { path = "../oak_baremetal_simple_io", optional = true }
rust-hypervisor-firmware-boot = { path = "../../third_party/rust-hypervisor-firmware-boot" }
rust-hypervisor-firmware-virtio = { path = "../../third_party/rust-hypervisor-firmware-virtio" }
strum = { version = "*", default-features = false, features = ["derive"] }
uart_16550 = "*"
virtio = { path = "../virtio", optional = true }
x86_64 = "*"
