[package]
name = "oak_baremetal_kernel"
version = "0.1.0"
authors = ["Andri Saar <andrisaar@google.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
default = []
vsock_channel = []
serial_channel = []

[dependencies]
anyhow = { version = "*", default-features = false }
arrayvec = { version = "*", default-features = false }
atomic_refcell = "*"
ciborium-io = { version = "*", default-features = false }
getrandom = { version = "0.2", features = ["rdrand"] }
lazy_static = { version = "*", features = ["spin_no_std"] }
linked_list_allocator = { version = "*" }
log = "*"
libm = "*"
oak_remote_attestation = { path = "../../remote_attestation/rust", default-features = false, features = [
  "rust-crypto"
] }
oak_baremetal_runtime = { path = "../../experimental/oak_baremetal_runtime", default-features = false, features = [
  "rust-crypto"
] }
rust-hypervisor-firmware-boot = { path = "../../third_party/rust-hypervisor-firmware-boot" }
rust-hypervisor-firmware-virtio = { path = "../../third_party/rust-hypervisor-firmware-virtio" }
strum = { version = "*", default-features = false, features = ["derive"] }
uart_16550 = "*"
virtio = { path = "../virtio" }
x86_64 = "*"
