[package]
name = "xtask"
version = "0.1.0"
authors = ["Tiziano Santoro <tzn@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
async-recursion = "*"
async-trait = "*"
cargo_metadata = "*"
chrono = { version = "*", default-features = false, features = [
  "std",
  "clock"
] }
clap = { version = "*", features = ["derive"] }
clap_complete = "*"
colored = "*"
itertools = "*"
maplit = "*"
nix = "*"
once_cell = "*"
regex = "*"
serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
strum = "0.24"
strum_macros = "0.24"
tokio = { version = "*", features = [
  "fs",
  "io-util",
  "macros",
  "process",
  "rt-multi-thread",
  "signal",
  "sync",
] }
toml = "*"
walkdir = "*"
