cargo-features = ["per-package-target"]

[package]
name = "mobilenet"
version = "0.1.0"
authors = ["Razieh Behjati <razieh@google.com>"]
edition = "2021"
license = "Apache-2.0"
forced-target = "wasm32-unknown-unknown"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "*"
oak_functions = { path = "../../../sdk/oak_functions", features = [
  "oak-unsafe"
] }
oak_functions_abi = { path = "../../../abi" }
prost = "*"
