name = "hello_world"

[applications]

[applications.rust]
manifest = "examples/hello_world/config.toml"
out = "examples/hello_world/bin/config.bin"

[applications.rust.modules]
module = { Cargo = { cargo_manifest = "examples/hello_world/module/rust/Cargo.toml" } }
translator = { Cargo = { cargo_manifest = "examples/translator/module/rust/Cargo.toml" } }

[applications.cpp]
manifest = "examples/hello_world/config_cpp.toml"
out = "examples/hello_world/bin/config_cpp.bin"

[applications.cpp.modules]
module = { Bazel = { bazel_target = "//examples/hello_world/module/cpp:hello_world_cpp.wasm", config = "wasm32" } }
translator = { Cargo = { cargo_manifest = "examples/translator/module/rust/Cargo.toml" } }

[clients]
cpp = { Bazel = { bazel_target = "//examples/hello_world/client:client" } }
nodejs = { Npm = { package_directory = "examples/hello_world/client/nodejs" } }
