[package]
name = "oak_utils"
version = "0.1.0"
authors = ["Ivan Petrov <ivanpetrov@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
prost = "*"
prost-build = "*"
tempfile = "*"
# Disable the `rustfmt` feature, as it requires `rustfmt` which may not be supported for custom
# toolchains.
tonic-build = { version = "*", default-features = false, features = [
  "prost",
  "transport"
] }
