cargo-features = ["per-package-target"]

[package]
name = "metrics_client"
version = "0.1.0"
authors = ["Conrad Grobler <grobler@google.com>"]
edition = "2021"
license = "Apache-2.0"
default-target = "x86_64-unknown-linux-musl"

[dependencies]
anyhow = "*"
clap = { version = "*", features = ["derive"] }
oak_functions_abi = { path = "../../../../abi" }
oak_functions_client = { path = "../../../../client/rust" }
tokio = { version = "*", features = [
  "fs",
  "macros",
  "sync",
  "rt-multi-thread"
] }
tonic = { version = "*", features = ["tls", "tls-roots"] }
