[package]
name = "chat_0_frontend"
version = "0.1.0"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
chat_common = { path = "../../common" }
log = "*"
oak = "=0.1.0"
oak_derive = "*"
oak_log = "*"
protobuf = "*"
rand_core = "^0.5"
rand = "^0.7"
