[package]
name = "oak_remote_attestation_sessions"
version = "0.1.0"
authors = ["Juliette Pretot <julsh@google.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
default = ["ring-crypto"]
ring-crypto = ["oak_remote_attestation/ring-crypto"]
rust-crypto = ["oak_remote_attestation/rust-crypto"]
client = ["async-trait", "rand"]

[dependencies]
anyhow = { version = "*", default-features = false }
oak_remote_attestation = { path = "../remote_attestation/rust/", default-features = false }
async-trait = { version = "*", optional = true }
rand = { version = "*", optional = true }
lru = "*"
