[package]
name = "oak_utils"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

[dependencies]
protoc-rust = "*"
protoc-rust-grpc = { path = "../../../third_party/grpc-rust/protoc-rust-grpc" }
tempfile = "*"
walkdir = "*"
