[package]
name = "snp_measurement"
version = "0.1.0"
authors = ["Conrad Grobler <grobler@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
clap = { version = "*", features = ["derive"] }
env_logger = "*"
goblin = "*"
hex = "*"
oak_sev_guest = { workspace = true }
log = "*"
sha2 = "*"
static_assertions = "*"
strum = { version = "*", default-features = false, features = ["derive"] }
x86_64 = "*"
zerocopy = { version = "*", features = ["derive"] }
