[package]
name = "sev_guest"
version = "0.1.0"
authors = ["Conrad Grobler <grobler@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
bitflags = "*"
lock_api = "*"
spinning_top = "*"
static_assertions = "*"
snafu = { version = "*", default-features = false }
strum = { version = "*", default-features = false, features = ["derive"] }
zerocopy = "*"
x86_64 = "*"
