name = "aggregator"

[application]
variant = "rust"
manifest = "examples/aggregator/config/config.toml"
out = "examples/aggregator/bin/config.bin"

[modules]
module = { Cargo = { cargo_manifest = "examples/aggregator/module/rust/Cargo.toml" } }

[clients]
cpp = { Bazel = { bazel_target = "//examples/aggregator/client:client" }, additional_args = [
  "--bucket=test",
  "--data=1:10,2:20,3:30"
] }
