name = "aggregator"

[applications]

[applications.rust]
manifest = "examples/aggregator/config.toml"
out = "examples/aggregator/bin/config.bin"

[applications.rust.modules]
module = { Cargo = { cargo_manifest = "examples/aggregator/module/rust/Cargo.toml" } }

[clients]
cpp = { Bazel = { bazel_target = "//examples/aggregator/client:client" }, additional_args = [
  "--bucket=test",
  "--data=1:10,2:20,3:30"
] }
