name = "aggregator"

[backends]
backend = { Cargo = { cargo_manifest = "examples/aggregator/backend/Cargo.toml" }, additional_args = [
  "--grpc-listen-address=[::]:8888",
  "--grpc-tls-private-key=./examples/certs/local/local.key",
  "--grpc-tls-certificate=./examples/certs/local/local.pem",
] }

[applications]

[applications.classic.rust]
manifest = "examples/aggregator/oak_app_manifest.toml"
out = "examples/aggregator/bin/aggregator.oak"

[applications.classic.rust.modules]
main_module = { Cargo = { cargo_manifest = "examples/aggregator/main_module/Cargo.toml" } }
handler_module = { Cargo = { cargo_manifest = "examples/aggregator/handler_module/Cargo.toml" } }

[server]
additional_args = ["--config-files=config=examples/aggregator/config.toml"]

[clients]
cpp = { Bazel = { bazel_target = "//examples/aggregator/client/cpp:client" }, additional_args = [
  "--bucket=test",
  "--data=1:10,2:20,3:30"
] }
