name = "aggregator"

[modules]
app = { path = "examples/aggregator/bin/aggregator.wasm" }
app = { external = { url = "https://storage.googleapis.com/oak-modules/aggregator/53d38904ac029db2f25d8a976ee4bf9060cd01c80e48e2c10d9cfcbedbec50de", sha256 = "53d38904ac029db2f25d8a976ee4bf9060cd01c80e48e2c10d9cfcbedbec50de" } }
