[package]
name = "machine_learning"
version = "0.1.0"
authors = ["Tiziano Santoro <tzn@google.com>"]
edition = "2018"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
rusty-machine = "*"
rand = "*"
rand_distr = "*"
oak = "=0.1.0"
oak_io = "=0.1.0"
log = "*"
prost = "*"
