[package]
name = "oak_remote_attestation_verification"
version = "0.1.0"
authors = ["Razieh Behjati <razieh@google.com>"]
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "*"
base64 = "*"
ecdsa = { version = "*", features = ["pkcs8", "pem"] }
hex = "*"
oak_transparency_claims = { workspace = true }
p256 = { version = "*", features = ["ecdsa-core", "ecdsa", "pem"] }
serde = { version = "*", features = ["derive"] }
serde_jcs = "*"
serde_json = "*"
sha2 = { version = "*", default-features = false }

[dev-dependencies]
oak_crypto = { workspace = true }

[build-dependencies]
micro_rpc_build = { workspace = true }
