[package]
name = "private_set_intersection_client"
version = "0.1.0"
authors = ["Ivan Petrov <ivanpetrov@google.com>"]
edition = "2018"
license = "Apache-2.0"

[lib]
name = "private_set_intersection_client"
path = "src/lib.rs"

[[bin]]
name = "psi_client_bin"
path = "src/main.rs"

[dependencies]
anyhow = "*"
base64 = "*"
env_logger = "*"
http = "*"
log = "*"
maplit = "*"
oak_abi = "=0.1.0"
oak_client = "=0.1.0"
oak_sign = "=0.1.0"
pem = "*"
prost = "*"
structopt = "*"
tokio = { version = "*", features = [
  "fs",
  "macros",
  "sync",
  "rt-multi-thread"
] }
tonic = { version = "*", features = ["tls"] }

[build-dependencies]
oak_utils = "*"
