[package]
name = "oak_functions_loader-fuzz"
version = "0.0.0"
authors = ["Razieh Behjati <razieh@google.com>"]
edition = "2021"
license = "Apache-2.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
anyhow = "*"
arbitrary = { version = "1", features = ["derive"] }
lazy_static = "*"
libfuzzer-sys = "*"
maplit = "*"
oak_functions_loader = { path = "..", features = ["oak-metrics"] }
oak_functions_abi = { path = "../../abi" }
oak_functions_metrics = { path = "../../experimental/metrics" }
prost = "*"
tokio = "*"
tonic = "*"

[build-dependencies]
prost-build = "*"

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "apply_policy"
path = "fuzz_targets/apply_policy.rs"
test = false
doc = false

[[bin]]
name = "wasm_invoke"
path = "fuzz_targets/wasm_invoke.rs"
test = false
doc = false
