[package]
name = "quirk_echo_launcher"
version = "0.1.0"
authors = ["Dzmitry Huba <huba@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
async-trait = "*"
bmrng = "*"
clap = { version = "*", features = ["derive"] }
command-fds = { version = "*", features = ["tokio"] }
futures = "*"
log = "*"
env_logger = "0.10.0"
prost = "0.11.2"
serde = "*"
tokio = { version = "*", features = [
  "rt-multi-thread",
  "macros",
  "net",
  "process",
  "signal",
  "sync",
] }
quirk_echo_service = { path = "../quirk_echo_service" }
micro_rpc = { path = "../micro_rpc" }
oak_channel = { path = "../oak_channel", features = ["client"] }
hashbrown = "*"

[build-dependencies]
micro_rpc_build = { path = "../micro_rpc_build" }

[dev-dependencies]
lazy_static = "*"
rand = "*"
