[package]
name = "oak_functions_abi"
version = "0.1.0"
authors = ["Razieh Behjati <razieh@google.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
oak-metrics = []
oak-tf = []

[dependencies]
prost = "*"
serde = "*"
serde_derive = "*"

[build-dependencies]
prost-build = "*"
