[package]
name = "tensorflow_proxy"
version = "0.1.0"
authors = ["Conrad Grobler <grobler@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
async-stream = "*"
anyhow = "*"
bytes = "*"
clap = { version = "*", features = ["derive"] }
env_logger = "*"
futures = "*"
grpc_attestation = { path = "../../../grpc_attestation/" }
oak_remote_attestation_amd = { path = "../../../oak_remote_attestation_amd/" }
http = "*"
log = "*"
oak_functions_abi = { path = "../../../oak_functions/abi" }
oak_utils = { path = "../../../oak_utils" }
oak_remote_attestation = { path = "../../../remote_attestation/rust/" }
prost = "*"
prost-types = "*"
sync_wrapper = "*"
tokio = { version = "*", features = [
  "fs",
  "macros",
  "process",
  "sync",
  "rt-multi-thread"
] }
tonic = "*"
tower = "*"
pin-project-lite = "*"

[build-dependencies]
oak_utils = { path = "../../../oak_utils" }
