[package]
name = "sev_serial"
version = "0.1.0"
authors = ["Conrad Grobler <grobler@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
sev_guest = { path = "../sev_guest" }
x86_64 = "*"
