[package]
name = "trusted_information_retrieval"
version = "0.1.0"
authors = ["Ivan Petrov <ivanpetrov@google.com>"]
edition = "2018"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "*"
database_proxy = "*"
log = "*"
oak = "=0.1.0"
oak_abi = "=0.1.0"
oak_services = "=0.1.0"
prost = "*"
serde = "*"
toml = "*"

[dev-dependencies]
assert_matches = "*"
env_logger = "*"
maplit = "*"
oak_abi = "=0.1.0"
oak_runtime = "=0.1.0"
oak_tests = "=0.1.0"
tokio = { version = "*", features = ["macros", "rt-threaded", "stream"] }
tonic = { version = "*", features = ["tls"] }
trusted_information_retrieval_client = "=0.1.0"

[build-dependencies]
oak_utils = "*"
