[package]
name = "oak_containers_orchestrator_client"
version = "0.1.0"
authors = ["Juliette Pretot <julsh@google.com>"]
edition = "2021"
license = "Apache-2.0"

[build-dependencies]
oak_grpc_utils = { workspace = true }

[dependencies]
anyhow = "*"
async-trait = { version = "*", default-features = false }
oak_crypto = { workspace = true }
oak_remote_attestation = { workspace = true }
opentelemetry-otlp = { version = "*", default-features = false, features = [
  "grpc-tonic",
  "logs",
  "metrics"
] }
prost = "*"
prost-types = "*"
tokio = { version = "*", features = ["rt-multi-thread", "macros", "sync"] }
tonic = "*"
tower = "*"
