[workspace]

[package]
name = "oak_functions_loader"
version = "0.1.0"
authors = ["Razieh Behjati <razieh@google.com>"]
edition = "2018"
license = "Apache-2.0"

[features]
# Feature that allows logging. Should be use only for debugging purposes.
oak-unsafe = []
default = []

[dependencies]
anyhow = "*"
env_logger = "*"
http = "*"
hyper = { version = "*", features = ["full"] }
log = "*"
structopt = "*"
tokio = { version = "*", features = [
  "fs",
  "macros",
  "sync",
  "rt-multi-thread"
] }
wasmi = "*"
