[package]
name = "oak_functions_loader"
version = "0.1.0"
authors = ["Razieh Behjati <razieh@google.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
oak-web = ["tonic-web"]

[dependencies]
anyhow = "*"
async-trait = "*"
async-stream = "*"
bytes = "*"
byteorder = { version = "*", default-features = false }
chrono = { version = "*", default-features = false, features = [
  "std",
  "clock"
] }
clap = { version = "*", features = ["derive"] }
futures = "*"
grpc_attestation = { path = "../../grpc_attestation/" }
oak_remote_attestation_amd = { path = "../../oak_remote_attestation_amd/" }
hashbrown = "*"
http = "*"
hyper = { version = "*", features = [
  "client",
  "http1",
  "http2",
  "runtime",
  "server"
] }
hyper-rustls = { version = "*" }
humantime-serde = "*"
# Logging via the log crate is disabled and only available using our own custom logger that
# implements the OakLogger trait defined in oak_functions/logger/src/lib.rs.
#
# This is done to avoid accidentally leaking information logged by dependencies and allow code
# to differentiate between public and potentially sensitive log messages.
# TODO(#2783): Re-enable logging via the log crate once the logging approach has been redisigned.
log = { version = "*", features = ["max_level_off", "release_max_level_off"] }
oak_functions_abi = { path = "../abi" }
oak_functions_extension = { path = "../extension" }
oak_functions_lookup = { path = "../lookup" }
oak_functions_util = { path = "../util" }
oak_functions_wasm = { path = "../wasm" }
oak_functions_workload_logging = { path = "../workload_logging" }
oak_logger = { path = "../logger" }
oak_utils = { path = "../../oak_utils" }
oak_remote_attestation = { path = "../../remote_attestation/rust/" }
prost = "*"
rand = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
tokio = { version = "*", features = [
  "fs",
  "macros",
  "sync",
  "rt-multi-thread"
] }
tonic = "*"
tonic-web = { version = "*", optional = true }
url = "*"
# Use wasmi in `no_std` mode.
wasmi = { version = "*", default-features = false, features = ["core"] }
signal-hook = "*"

[dev-dependencies]
criterion = "*"
lookup_data_generator = { path = "../lookup_data_generator" }
maplit = "*"
tempfile = "*"
test_utils = { path = "../sdk/test_utils" }

[build-dependencies]
oak_utils = { path = "../../oak_utils" }

[[bench]]
name = "lookup"
harness = false
