[package]
name = "oak_remote_attestation"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
futures-util = "*"
oak_crypto = { workspace = true }
micro_rpc = { workspace = true }
prost = { workspace = true }

[build-dependencies]
micro_rpc_build = { workspace = true }
