[package]
name = "machine_learning"
version = "0.1.0"
authors = ["Tiziano Santoro <tzn@google.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
rusty-machine = "*"
rand = "*"
oak = { path = "../../rust/oak" }
