name = "machine_learning"

[application]
variant = "rust"
manifest = "examples/machine_learning/config/config.toml"
out = "examples/machine_learning/bin/config.bin"

[modules]
module = { Cargo = { cargo_manifest = "examples/machine_learning/module/rust/Cargo.toml" } }

[clients]
cpp = { Bazel = { bazel_target = "//examples/machine_learning/client:client" } }
