[workspace]

members = [
  "oak_abi",
  "oak_runtime",
]

# Patch dependencies on oak crates so that they refer to the versions within this same repository.
#
# From https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html :
# > Cargo doesnâ€™t assume that crates in a workspace will depend on each other, so we need to be
# > explicit about the dependency relationships between the crates.
[patch.crates-io]
oak = { path = "../../../sdk/rust/oak" }
oak_abi = { path = "oak_abi" }
oak_runtime = { path = "oak_runtime" }
oak_utils = { path = "../../common/rust/utils" }
