[package]
name = "key_xor_test_app"
version = "0.1.0"
authors = ["Conrad Grobler <grobler@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
log = "*"
micro_rpc = { workspace = true }
oak_channel = { workspace = true }
oak_restricted_kernel_sdk = { workspace = true }
oak_restricted_kernel_interface = { workspace = true }
static_assertions = "*"

[[bin]]
name = "key_xor_test_app"
test = false
bench = false
