# Unlike other build configs, this one needs to run in the "default" shell instead of just the
# "rust" one, because bazel is also used by the build.rs script.
command = [
  "nix",
  "develop",
  ".#default",
  "--command",
  "env",
  "--chdir=enclave_apps/oak_tensorflow_enclave_app",
  "cargo",
  "build",
  "--release"
]
artifact_path = "./enclave_apps/target/x86_64-unknown-none/release/oak_tensorflow_enclave_app"
