command = [
  "env",
  "--chdir=oak_ml_transparency/mnist",
  "/project/runner-musl",
  "--model=/project/mnist_model.tar.gz",
  "--model-name=mnist",
  "--eval-script=/project/eval.py",
  "--output=claim.json",
]
artifact_path = "./oak_ml_transparency/mnist/claim.json"
binary_file = ""
package_name = ""
