command = [
  "nix",
  "develop",
  ".#rust",
  "--command",
  "env",
  "--chdir=enclave_apps/oak_orchestrator",
  "cargo",
  "build",
  "--release",
]
artifact_path = "./enclave_apps/target/x86_64-unknown-none/release/oak_orchestrator"
binary_file = "./enclave_apps/target/x86_64-unknown-none/release/oak_orchestrator"
package_name = "oak_orchestrator"
