[package]
name = "oak_functions_sdk"
version = "0.1.0"
authors = ["Razieh Behjati <razieh@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
micro_rpc = { workspace = true }
oak_functions_abi = { workspace = true }
prost = { workspace = true }

[build-dependencies]
micro_rpc_build = { workspace = true }

[dev-dependencies]
lazy_static = "*"
oak_functions_test_utils = { workspace = true }
oak_functions_service = { workspace = true }
tokio = "*"
