[package]
name = "oak_functions_tf_inference"
version = "0.1.0"
authors = ["Conrad Grobler <grobler@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
bytes = "*"
bincode = "*"
log = "*"
oak_functions_abi = { path = "../../abi" }
oak_functions_extension = { path = "../../extension" }
oak_logger = { path = "../../logger" }
prost = "*"
serde = "*"
serde_derive = "*"
tract-tensorflow = "*"
