[workspace]

members = [
    "abitest/abitest_common",
    "abitest/module_0/rust",
    "abitest/module_1/rust",
    "abitest/tests",
    "chat/module/rust",
    "hello_world/module/rust",
    "machine_learning/module/rust",
    "private_set_intersection/module/rust",
    "running_average/module/rust",
    "rustfmt/module/rust",
    "translator/common",
    "translator/module/rust",
]

[patch.crates-io]
# TODO: Remove when https://github.com/soc/dirs-rs/pull/24 is published.
dirs = { git = "https://github.com/soc/dirs-rs", rev = "910b3561557dfa8034d39e1462a6cedadbfb6b6e" }
# TODO: Remove when a new version of the term crate is published. The one currently published
# depends on dirs=1.0.2 which means that it does not pick up the fix above, which is done on
# dirs=2.0.1.
term = { git = "https://github.com/Stebalien/term", rev = "11e754980706a53dda998ba5791a203ab3a5f8fa" }

# Patch dependencies on oak crates so that they refer to the versions within this same repository.
oak = { path = "../sdk/rust/oak" }
oak_abi = { path = "../oak/server/rust/oak_abi" }
oak_derive = { path = "../sdk/rust/oak_derive" }
oak_log = { path = "../sdk/rust/oak_log" }
oak_runtime = { path = "../oak/server/rust/oak_runtime" }
oak_tests = { path = "../sdk/rust/oak_tests" }
oak_utils = { path = "../sdk/rust/oak_utils" }
translator_common = { path = "translator/common" }
