[package]
name = "running_average"
version = "0.1.0"
authors = ["Tiziano Santoro <tzn@google.com>"]
edition = "2018"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "*"
oak = "=0.1.0"
prost = "*"

[dev-dependencies]
assert_matches = "*"
env_logger = "*"
log = "*"
oak_abi = "=0.1.0"
oak_runtime = "=0.1.0"
oak_tests = "=0.1.0"
running_average_grpc = "=0.1.0"
tokio = { version = "*", features = ["macros", "rt-threaded", "stream"] }
tonic = { version = "*", features = ["tls"] }

[build-dependencies]
oak_utils = "*"
