[package]
name = "oak_echo"
version = "0.1.0"
authors = ["Ivan Petrov <ivanpetrov@google.com>"]
edition = "2021"
license = "Apache-2.0"

[workspace]
resolver = "2"
members = ["."]

[features]
default = ["vsock_channel"]
vsock_channel = ["oak_baremetal_kernel/vsock_channel"]
simple_io_channel = ["oak_baremetal_kernel/simple_io_channel"]

[dependencies]
oak_echo_runtime = { path = "../oak_echo_runtime" }
log = "*"
oak_baremetal_communication_channel = { path = "../../experimental/oak_baremetal_channel" }
oak_baremetal_kernel = { path = "../../experimental/oak_baremetal_kernel", default-features = false }
oak_idl = { path = "../../oak_idl" }
static_assertions = "*"

[[bin]]
name = "oak_echo"
test = false
bench = false
