cargo-features = ["per-package-target"]

[package]
name = "oak_functions_freestanding_bin"
version = "0.1.0"
authors = ["Andri Saar <andrisaar@google.com>"]
edition = "2021"
license = "Apache-2.0"
forced-target = "x86_64-unknown-none"

[features]
default = ["vsock_channel"]
vsock_channel = ["oak_restricted_kernel/vsock_channel"]
simple_io_channel = ["oak_restricted_kernel/simple_io_channel"]
serial_channel = ["oak_restricted_kernel/serial_channel"]

[dependencies]
log = "*"
oak_channel = { path = "../oak_channel" }
oak_restricted_kernel = { path = "../oak_restricted_kernel", default-features = false }
oak_functions_freestanding = { path = "../oak_functions_freestanding", default-features = false }
oak_linux_boot_params = { path = "../linux_boot_params" }
oak_remote_attestation = { path = "../oak_remote_attestation", default-features = false, features = [
  "rust-crypto"
] }
oak_remote_attestation_amd = { path = "../oak_remote_attestation_amd", default-features = false, features = [
  "rust-crypto"
] }
oak_idl = { path = "../oak_idl" }
static_assertions = "*"

[[bin]]
name = "oak_functions_freestanding_bin"
test = false
bench = false
