[package]
name = "oak_lookup_enclave_app"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
oak_functions_service = { path = "../../oak_functions_service", default-features = false }
oak_lookup_service = { path = "../../oak_lookup_service", default-features = false }
log = "*"
micro_rpc = { workspace = true }
oak_enclave_runtime_support = { workspace = true }
oak_channel = { workspace = true }
oak_remote_attestation_interactive = { workspace = true }
oak_remote_attestation_amd = { workspace = true }
oak_restricted_kernel_api = { workspace = true }
static_assertions = "*"

[[bin]]
name = "oak_lookup_enclave_app"
test = false
bench = false
