[workspace]

[package]
name = "oak_runtime"
version = "0.1.0"
authors = [
  "David Drysdale <drysdale@google.com>",
  "Ben Blaxill<benblaxill@google.com>"
]
edition = "2018"
license = "Apache-2.0"

[features]
oak_debug = ["regex"]
oak_introspection_client = []
default = ["oak_debug"]

[dependencies]
anyhow = "*"
byteorder = { version = "*", default-features = false }
bytes = "*"
base64 = "*"
chrono = "*"
futures-core = "*"
futures-util = "*"
hex = "*"
http = "*"
hyper = "*"
hyper-rustls = { version = "*", default-features = false, features = [
  "webpki-tokio"
] }
itertools = "*"
jsonwebtoken = "*"
lazy_static = "*"
log = { version = "*" }
maplit = "*"
oak_abi = { path = "../oak_abi" }
oak_io = { path = "../oak_io" }
oak_services = { path = "../oak_services" }
oak_sign = { path = "../oak_sign" }
prometheus = { version = "0.10", features = [
  "nightly"
], default-features = false }
prost = { path = "../third_party/prost" }
prost-types = { path = "../third_party/prost/prost-types" }
rand = "*"
regex = { version = "1", optional = true }
reqwest = { version = "*", default-features = false, features = ["rustls-tls"] }
roughenough = { path = "../third_party/roughenough" }
rustls = "*"
serde = "*"
serde_json = "*"
sha2 = "^0.9.1"
tink-core = { version = "^0.1", features = ["json"] }
tink-aead = "^0.1"
tink-awskms = "^0.1"
tink-daead = "^0.1"
# TODO(#745): sort out clashing dependencies
# tink-gcpkms = "^0.1"
tink-mac = "^0.1"
tink-prf = "^0.1"
tink-proto = "^0.1"
tink-signature = "^0.1"
# Pinned to 0.2 because of tonic: https://github.com/hyperium/tonic/blob/master/tonic/Cargo.toml
tokio = { version = "0.2", features = [
  "dns",
  "io-driver",
  "io-util",
  "macros",
  "rt-core",
  "time",
  "udp"
] }
tokio-rustls = "*"
tonic = { version = "*", features = ["tls"] }
wasmi = { version = "*", default-features = false, features = ["core"] }

[dev-dependencies]
env_logger = "*"
hyper-rustls = { version = "*", default-features = false, features = [
  "webpki-tokio"
] }
regex = "*"
wat = "*"

[build-dependencies]
oak_utils = { path = "../oak_utils" }
prost-build = { path = "../third_party/prost/prost-build" }

[patch.crates-io]
prost = { path = "../third_party/prost" }
prost-build = { path = "../third_party/prost/prost-build" }
prost-derive = { path = "../third_party/prost/prost-derive" }
prost-types = { path = "../third_party/prost/prost-types" }
