[workspace]

[package]
name = "oak_runtime"
version = "0.1.0"
authors = [
  "David Drysdale <drysdale@google.com>",
  "Ben Blaxill<benblaxill@google.com>"
]
edition = "2018"
license = "Apache-2.0"

[features]
test_build = []
oak_debug = ["regex"]
oak_introspection_client = []
default = ["oak_debug"]

[dependencies]
byteorder = { version = "*", default-features = false }
bytes = "*"
base64 = "*"
futures = "*"
futures-core = "*"
futures-util = "*"
hex = "*"
http = "*"
hyper = "*"
itertools = "*"
jsonwebtoken = "*"
lazy_static = "*"
log = { version = "*" }
maplit = "*"
oak_abi = { path = "../oak_abi" }
oak_io = { path = "../oak_io" }
oak_services = { path = "../oak_services" }
pem = "*"
prometheus = { version = "0.10", features = [
  "nightly"
], default-features = false }
prost = { path = "../third_party/prost" }
prost-types = { path = "../third_party/prost/prost-types" }
rand = "*"
regex = { version = "1", optional = true }
reqwest = { version = "*", default-features = false, features = ["rustls-tls"] }
ring = "*"
roughenough = { path = "../third_party/roughenough" }
rustls = "*"
serde = "*"
serde_json = "*"
sha2 = "*"
tokio = { version = "*", features = [
  "dns",
  "io-driver",
  "macros",
  "rt-core",
  "time",
  "udp"
] }
tokio-rustls = "*"
tonic = { version = "*", features = ["tls"] }
wasmi = { version = "*", default-features = false, features = ["core"] }

[dev-dependencies]
env_logger = "*"
hyper-rustls = { version = "*", default-features = false, features = [
  "webpki-tokio"
] }
minisign = "*"
regex = "*"
wat = "*"

[build-dependencies]
oak_utils = { path = "../oak_utils" }
prost-build = { path = "../third_party/prost/prost-build" }

[patch.crates-io]
prost = { path = "../third_party/prost" }
prost-build = { path = "../third_party/prost/prost-build" }
prost-derive = { path = "../third_party/prost/prost-derive" }
prost-types = { path = "../third_party/prost/prost-types" }
