[package]
name = "key_value_lookup_test"
version = "0.1.0"
authors = ["Maria Schett <mschett@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
oak_functions = { path = "../../sdk/oak_functions" }

[dev-dependencies]
oak_functions_loader = { path = "../../loader" }
oak_functions_abi = { path = "../../abi" }
http = "*"
hyper = { version = "*", features = ["client", "http2"] }
maplit = "*"
prost = "*"
test_utils = { path = "../../sdk/test_utils" }
tokio = { version = "*", features = [
  "fs",
  "macros",
  "sync",
  "rt-multi-thread"
] }
