lookup_data = { Url = "https://storage.googleapis.com/oak_lookup_data/lookup_data_weather" }
lookup_data_download_period = "10m"
worker_threads = 4

[policy]
constant_response_size_bytes = 90
constant_processing_time = "20ms"
