[package]
name = "oak_functions_test_utils"
version = "0.1.0"
authors = ["Razieh Behjati <razieh@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
command-group = "*"
log = "*"
http = "*"
hyper = { version = "*", features = ["client", "http1", "runtime", "server"] }
nix = { version = "*", features = ["process", "signal"] }
oak_client = { workspace = true }
oak_functions_abi = { workspace = true }
oak_functions_client = { workspace = true }
oak_proto_rust = { workspace = true }
once_cell = "*"
port_check = "*"
prost = { workspace = true }
portpicker = "*"
tempfile = "*"
tokio = { workspace = true, features = ["sync"] }
ubyte = "*"
