[package]
name = "oak_tests"
version = "0.1.0"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
byteorder = "*"
lazy_static = "*"
log = { version = "*", features = ["std"] }
oak = "=0.1.0"
oak_abi = "=0.1.0"
oak_runtime = { version = "=0.1.0", features = ["test_build"] }
protobuf = "*"
rand = { version = "*" }
cargo_metadata = "*"

[build-dependencies]
protoc-rust = "*"
