[package]
name = "oak_client_tonic"
version = "0.1.0"
authors = ["Ivan Petrov <ivanpetrov@google.com>"]
edition = "2021"
license = "Apache-2.0"

[lib]
path = "lib.rs"

[dependencies]
anyhow = "*"
async-trait = "*"
futures = "*"
log = "*"
oak_client = { workspace = true }
oak_proto_rust = { workspace = true }
prost = { workspace = true }
tonic = { workspace = true }
