[package]
name = "oak_containers_stage1"
version = "0.1.0"
edition = "2021"
authors = ["Andri Saar <andrisaar@google.com>"]
license = "Apache-2.0"

[build-dependencies]
oak_grpc_utils = { workspace = true }

[dependencies]
anyhow = "*"
ciborium = { version = "*", default-features = false }
clap = { version = "*", features = ["derive"] }
coset = { version = "*", features = ["std"] }
futures-util = "*"
oak_attestation = { workspace = true }
oak_crypto = { workspace = true }
oak_dice = { workspace = true }
oak_proto_rust = { workspace = true }
nix = { version = "*", features = ["mman"] }
p256 = { version = "*" }
prost = { workspace = true }
prost-types = "*"
rand_core = { version = "*", default-features = false, features = [
  "getrandom",
] }
rtnetlink = "*"
sha2 = { version = "*", default-features = false }
tar = "*"
tokio = { version = "*", features = [
  "rt-multi-thread",
  "macros",
  "process",
  "sync",
] }
tokio-vsock = { version = "*", features = ["tonic-conn"] }
tonic = { workspace = true }
tower = "*"
x86_64 = "*"
xz2 = "*"
zerocopy = "*"
zeroize = "*"
