[package]
name = "http_server"
version = "0.1.0"
authors = ["Razieh Behjati <razieh@google.com>"]
edition = "2018"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "*"
maplit = "*"
oak = "=0.1.0"
oak_abi = "=0.1.0"
oak_services = "=0.1.0"
