[package]
name = "uefi-simple"
version = "0.1.0"
authors = ["Andri Saar <andrisaar@google.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
default = ["support_emulated_runner"]
support_emulated_runner = []

[dependencies]
anyhow = { version = "*", default-features = false }
oak_remote_attestation = { path = "../../../remote_attestation/rust" }
runtime = { path = "../runtime" }
uefi = { version = "*", features = ["exts"] }
uefi-services = "*"
ciborium-io = { version = "*", default-features = false }

[dev-dependencies]
uefi-services = { version = "*", features = ["qemu"] }
