[package]
name = "uefi-simple"
version = "0.1.0"
authors = ["Andri Saar <andrisaar@google.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
default = []
kvm = []

[dependencies]
uefi = { version = "*", features = ["exts"] }
uefi-services = "*"
log = { version = "*" }
ciborium = { version = "*", default-features = false }
ciborium-io = "*"
oak_remote_attestation = { path = "../../../remote_attestation/rust" }

[dev-dependencies]
anyhow = { version = "*", default-features = false }
uefi-services = { version = "*", features = ["qemu"] }
