[package]
name = "uefi-simple"
version = "0.1.0"
authors = ["Andri Saar <andrisaar@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
uefi = { version = "*", features = ["exts"] }
uefi-services = "*"
log = { version = "*" }
oak_remote_attestation = { path = "../../../remote_attestation/rust" }
anyhow = { version = "*", default-features = false }

[dev-dependencies]
uefi-services = { version = "*", features = ["qemu"] }
