[package]
name = "oak"
version = "0.1.0"
authors = ["Tiziano Santoro <tzn@google.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
oak_abi = "=0.1.0"
protobuf = "*"
fmt = "*"
log = "*"
byteorder = "*"
rand_core = { version = "*", features = ["std"] }
serde = { version = "*", features = ["derive"] }

[build-dependencies]
protoc-rust = "*"

[dev-dependencies]
assert_matches = "*"
oak_derive = "=0.1.0"
oak_tests = "=0.1.0"
serial_test = "*"
serial_test_derive = "*"
serde_json = "*"
