[workspace]

[package]
name = "oak_loader"
version = "0.1.0"
authors = [
  "Ivan Petrov <ivanpetrov@google.com>",
  "David Drysdale <drysdale@google.com>"
]
edition = "2018"
license = "Apache-2.0"

[features]
oak_debug = []
default = ["oak_debug"]

[dependencies]
anyhow = "*"
env_logger = "*"
log = "*"
oak_abi = { path = "../oak_abi" }
oak_runtime = { path = "../oak_runtime" }
oak_utils = { path = "../oak_utils" }
prost = { path = "../third_party/prost" }
rustls = "*"
serde = { version = "*", features = ["derive"] }
signal-hook = "*"
structopt = "*"
toml = "*"
tonic = { version = "*", features = ["tls"] }

[dev-dependencies]
maplit = "*"

[patch.crates-io]
prost = { path = "../third_party/prost" }
prost-derive = { path = "../third_party/prost/prost-derive" }
prost-build = { path = "../third_party/prost/prost-build" }
prost-types = { path = "../third_party/prost/prost-types" }
