[package]
name = "treehouse"
version = "0.1.0"
authors = ["Tiziano Santoro <tzn@google.com>"]
edition = "2018"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "*"
log = "*"
oak = "=0.1.0"
oak_abi = "=0.1.0"
oak_io = "=0.1.0"
oak_services = "=0.1.0"
prost = "*"

[build-dependencies]
oak_utils = "*"
