[workspace]
members = ["rust/oak_loader", "rust/oak_runtime"]

# Patch dependencies on oak crates so that they refer to the versions within this same repository.
#
# From https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html :
# > Cargo doesnâ€™t assume that crates in a workspace will depend on each other, so we need to be
# > explicit about the dependency relationships between the crates.
[patch.crates-io]
# Oak.
oak_abi = { path = "../../oak_abi" }
oak_io = { path = "../../oak_io" }
oak_loader = { path = "rust/oak_loader" }
oak_runtime = { path = "rust/oak_runtime" }
oak_services = { path = "../../oak_services" }
oak_utils = { path = "../../oak_utils" }
# Third party.
roughenough = { path = "../../third_party/roughenough" }
prost = { path = "../../third_party/prost" }
prost-derive = { path = "../../third_party/prost/prost-derive" }
prost-build = { path = "../../third_party/prost/prost-build" }
prost-types = { path = "../../third_party/prost/prost-types" }
