[package]
name = "oak_simple_io"
version = "0.1.0"
authors = ["Conrad Grobler <grobler@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
oak_sev_snp_guest = { workspace = true }
x86_64 = "*"
