[package]
name = "oak_restricted_kernel_bin"
version = "0.1.0"
authors = ["Andri Saar <andrisaar@google.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
default = ["virtio_console_channel"]
virtio_console_channel = ["oak_restricted_kernel/virtio_console_channel"]
vsock_channel = ["oak_restricted_kernel/vsock_channel"]
simple_io_channel = ["oak_restricted_kernel/simple_io_channel"]
serial_channel = ["oak_restricted_kernel/serial_channel"]

[workspace]
resolver = "2"
members = ["."]

[dependencies]
log = "*"
oak_linux_boot_params = { path = "../oak_linux_boot_params" }
oak_restricted_kernel = { path = "../oak_restricted_kernel", default-features = false }

[[bin]]
name = "oak_restricted_kernel_bin"
test = false
bench = false
required-features = ["virtio_console_channel"]

[[bin]]
path = "src/main.rs"
name = "oak_restricted_kernel_simple_io_init_rd_bin"
test = false
bench = false
required-features = ["simple_io_channel"]
