[package]
name = "hello_world"
version = "0.1.0"
authors = ["Razieh Behjati <razieh@google.com>"]
edition = "2018"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "*"
oak_functions = "0.1.0"

[dev-dependencies]
env_logger = "*"
oak_functions_loader = "0.1.0"
http = "*"
hyper = { version = "*", features = ["client"] }
test_utils = "0.1.0"
tokio = { version = "*", features = [
  "fs",
  "macros",
  "sync",
  "rt-multi-thread"
] }
