[workspace]
members = [
  "rust/oak",
  "rust/oak_app_build",
  "rust/oak_derive",
  "rust/oak_tests"
]

# Patch dependencies on oak crates so that they refer to the versions within this same repository.
#
# From https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html :
# > Cargo doesnâ€™t assume that crates in a workspace will depend on each other, so we need to be
# > explicit about the dependency relationships between the crates.
[patch.crates-io]
# Oak.
oak = { path = "rust/oak" }
oak_abi = { path = "../oak_abi" }
oak_app_build = { path = "rust/oak_app_build" }
oak_derive = { path = "rust/oak_derive" }
oak_io = { path = "../oak_io" }
oak_runtime = { path = "../oak/server/rust/oak_runtime" }
oak_services = { path = "../oak_services" }
oak_tests = { path = "rust/oak_tests" }
oak_utils = { path = "../oak_utils" }
# Third party.
roughenough = { path = "../third_party/roughenough" }
prost = { path = "../third_party/prost" }
prost-build = { path = "../third_party/prost/prost-build" }
prost-derive = { path = "../third_party/prost/prost-derive" }
prost-types = { path = "../third_party/prost/prost-types" }
