name = "tensorflow"

[application]
variant = "cpp"
manifest = "examples/tensorflow/config/config_cpp.toml"
out = "examples/tensorflow/bin/config_cpp.bin"

[modules]
module = { Bazel = { bazel_target = "//examples/tensorflow/module/cpp:tensorflow_micro.wasm", config = "emscripten" } }

[clients]
cpp = { Bazel = { bazel_target = "//examples/tensorflow/client:client" } }
