name = "tensorflow"

[applications]

[applications.cpp]
manifest = "examples/tensorflow/oak_app_manifest.toml"
out = "examples/tensorflow/bin/tensorflow.oak"

[applications.cpp.modules]
module = { Bazel = { bazel_target = "//examples/tensorflow/module/cpp:tensorflow_micro.wasm", config = "emscripten" } }

[clients]
cpp = { Bazel = { bazel_target = "//examples/tensorflow/client:client" } }
