[package]
name = "mcp_server"
version = "0.1.0"
authors = ["Ivan Petrov <ivanpetrov@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
env_logger = "*"
log = "*"
rmcp = { version = "0.1", features = [
    "server",
    "transport-io",
] }
serde = { version = "*", features = ["derive"] }
tokio = { version = "*", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "io-std",
    "signal",
] }
