[package]
name = "auth_client"
version = "0.1.0"
authors = ["grobler <grobler@google.com>"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
env_logger = "*"
futures = "*"
futures-util = { version = "*", default-features = false }
hyper = "*"
log = "*"
open = "*"
prost = "*"
structopt = "*"
tokio = { version = "*", features = ["fs", "macros", "sync", "stream"] }
tonic = { version = "*", features = ["tls"] }
url = "*"

[build-dependencies]
tonic-build = "*"
