[package]
name = "oak_functions_linux_fd_bin"
version = "0.1.0"
authors = ["Juliette Pretot <julsh@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
log = "*"
anyhow = { version = "*", default-features = false }
clap = { version = "*", features = ["derive"] }
oak_remote_attestation_interactive = { workspace = true }
oak_channel = { workspace = true, features = ["std"] }
oak_functions_service = { workspace = true }
oak_remote_attestation_amd = { workspace = true }
