[package]
name = "oak_functions_wasm"
version = "0.1.0"
authors = ["Conrad Grobler <grobler@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = { version = "*", default-features = false }
byteorder = { version = "*", default-features = false }
hashbrown = "*"
log = "*"
micro_rpc = { workspace = true }
oak_logger = { workspace = true }
oak_functions_abi = { workspace = true }
oak_functions_lookup = { workspace = true }
oak_functions_sdk = { workspace = true }
spinning_top = "*"
# Use wasmi in `no_std` mode.
wasmi = { version = "*", default-features = false }

[dev-dependencies]
oak_functions_test_utils = { workspace = true }
