[workspace]

[package]
name = "runner"
version = "0.1.0"
authors = ["Tiziano Santoro <tzn@google.com>"]
edition = "2018"
license = "Apache-2.0"

[build-dependencies]
platforms = "*"

[dependencies]
async-recursion = "*"
async-trait = "*"
chrono = "*"
clap = "*"
colored = "*"
platforms = "*"
lazy_static = "*"
maplit = "*"
nix = "*"
once_cell = "*"
regex = "*"
serde = { version = "*", features = ["derive"] }
structopt = "*"
tokio = { version = "*", features = [
  "fs",
  "io-util",
  "macros",
  "process",
  "rt-multi-thread",
  "signal",
  "stream",
  "sync",
] }
toml = "*"
walkdir = "*"
