[workspace]

[package]
name = "runner"
version = "0.1.0"
authors = ["Tiziano Santoro <tzn@google.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
colored = "*"
maplit = "*"
nix = "*"
notify = "5.0.0-pre.2"
serde = { version = "*", features = ["derive"] }
spinners = "*"
structopt = "*"
toml = "*"
walkdir = "*"
