[package]
name = "split_grpc_server"
version = "0.1.0"
authors = ["Conrad Grobler <grobler@google.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
futures-core = "*"
futures-util = "*"
prost = "*"
tokio = { version = "*", features = ["fs", "macros", "sync", "stream"] }
tonic = { version = "*", features = ["tls"] }

[build-dependencies]
tonic-build = "*"
