[workspace]

members = [
  "oak",
  "oak_derive",
  "oak_log",
  "oak_tests",
]

# Patch dependencies on oak crates so that they refer to the versions within this same repository.
#
# From https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html :
# > Cargo doesnâ€™t assume that crates in a workspace will depend on each other, so we need to be
# > explicit about the dependency relationships between the crates.
[patch.crates-io]
oak = { path = "oak" }
oak_abi = { path = "../../oak/server/rust/oak_abi" }
oak_derive = { path = "oak_derive" }
oak_log = { path = "oak_log" }
oak_runtime = { path = "../../oak/server/rust/oak_runtime" }
oak_tests = { path = "oak_tests" }
oak_utils = { path = "../oak/common/rust/utils" }
