name = "chat"

[modules]
module = { Cargo = { cargo_manifest = "examples/chat/module/rust/Cargo.toml" } }

[clients]
cpp = { Bazel = { bazel_target = "//examples/chat/client:client" }, additional_args = [
    "--test"
] }
