name = "private_set_intersection"

[applications]

[applications.rust]
manifest = "examples/private_set_intersection/oak_app_manifest.toml"
out = "examples/private_set_intersection/bin/private_set_intersection.oak"

[applications.rust.modules]
module = { Cargo = { cargo_manifest = "examples/private_set_intersection/module/rust/Cargo.toml" } }

[server]
additional_args = [
  "--signatures-manifest=examples/private_set_intersection/signatures.toml"
]

[clients]
cpp = { Bazel = { bazel_target = "//examples/private_set_intersection/client:client" } }
