name = "private_set_intersection"

[application]
build = { Shell = { script = "examples/private_set_intersection/config/build.sh" } }
out = "examples/private_set_intersection/bin/config.bin"

[modules]
module = { Cargo = { cargo_manifest = "examples/private_set_intersection/module/rust/Cargo.toml" } }

[clients]
cpp = { Bazel = { bazel_target = "//examples/private_set_intersection/client:client" } }
