name = "running_average"

[applications]

[applications.rust]
manifest = "examples/running_average/config.toml"
out = "examples/running_average/bin/config.bin"

[applications.rust.modules]
module = { Cargo = { cargo_manifest = "examples/running_average/module/rust/Cargo.toml" } }

[clients]
cpp = { Bazel = { bazel_target = "//examples/running_average/client:client" } }
