name = "running_average"

[application]
variant = "rust"
manifest = "examples/running_average/config/config.toml"
out = "examples/running_average/bin/config.bin"

[modules]
module = { Cargo = { cargo_manifest = "examples/running_average/module/rust/Cargo.toml" } }

[clients]
cpp = { Bazel = { bazel_target = "//examples/running_average/client:client" } }
