[build]
target = "x86_64-unknown-uefi"

[target.x86_64-unknown-uefi]
runner = "qemu-system-x86_64 -enable-kvm -cpu Broadwell-IBRS -nodefaults -nographic -bios /usr/share/OVMF/OVMF_CODE.fd -serial file:target/console.log -serial stdio -machine q35 -device isa-debug-exit,iobase=0xf4,iosize=0x04 -kernel"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]
