[workspace]
resolver = "2"
members = [
  "key_xor_test_app",
  "oak_echo_enclave_app",
  "oak_functions_enclave_app",
  "oak_echo_raw_enclave_app",
  "quirk_echo_enclave_app",
]

[workspace.dependencies]
micro_rpc = { path = "../micro_rpc" }
oak_enclave_runtime_support = { path = "../oak_enclave_runtime_support" }
oak_channel = { path = "../oak_channel" }
oak_core = { path = "../oak_core" }
oak_restricted_kernel_api = { path = "../oak_restricted_kernel_api" }
oak_restricted_kernel_interface = { path = "../oak_restricted_kernel_interface" }
oak_remote_attestation = { path = "../oak_remote_attestation" }
