[workspace]
resolver = "2"
members = [
  "oak_echo_enclave_app",
  "oak_echo_raw_enclave_app",
  "oak_functions_enclave_app",
  "oak_iree_enclave_app",
  "oak_lookup_enclave_app",
  "oak_tensorflow_enclave_app",
  "quirk_echo_enclave_app",
]

[workspace.dependencies]
micro_rpc = { path = "../micro_rpc" }
oak_enclave_runtime_support = { path = "../oak_enclave_runtime_support" }
oak_channel = { path = "../oak_channel" }
oak_restricted_kernel_api = { path = "../oak_restricted_kernel_api" }
oak_remote_attestation_interactive = { path = "../oak_remote_attestation_interactive", default-features = false, features = [
  "rust-crypto"
] }
oak_remote_attestation_amd = { path = "../oak_remote_attestation_amd", default-features = false, features = [
  "rust-crypto"
] }
